[package]
name = "trie_tree"
version = "0.1.0"
authors = ["MwlLj <731025894@qq.com>"]
edition = "2020"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
